image: golang:1.10.3

stages:
  - test
  - build
  - use

test:
  stage: test
  before_script:
    # see https://gitlab.com/gitlab-org/gitlab-runner/issues/1918
    # CI_PROJECT_DIR didn't worked…
    - mkdir -p $GOPATH/src/github.com/rande
    - ln -s $CI_PROJECT_DIR $GOPATH/src/github.com/rande/gitlab-ci-helper
    - cd $GOPATH/src/github.com/rande/gitlab-ci-helper
    - make install --no-print-directory
  script:
    - make test --no-print-directory

build:
  stage: build
  before_script:
    # see https://gitlab.com/gitlab-org/gitlab-runner/issues/1918
    # CI_PROJECT_DIR didn't worked…
    - mkdir -p $GOPATH/src/github.com/rande
    - ln -s $CI_PROJECT_DIR $GOPATH/src/github.com/rande/gitlab-ci-helper
    - cd $GOPATH/src/github.com/rande/gitlab-ci-helper
    - make install --no-print-directory
  script:
    - make build --no-print-directory
  artifacts:
    when:      always
    expire_in: 1 day
    paths:
      - build

use:
  stage: use
  before_script: []
  dependencies:
    - build
  script:
    - ./build/linux-amd64-gitlab-ci-helper --help
    - ./build/linux-amd64-gitlab-ci-helper version
    - ./build/linux-amd64-gitlab-ci-helper dump-rev
    - cat REVISION && echo ""
    - ./build/linux-amd64-gitlab-ci-helper dump-meta --verbose
    - cat ci.json && echo ""
    # GITLAB_HOST & GITLAB_TOKEN should be set in CI/CD variables
    - ./build/linux-amd64-gitlab-ci-helper envs add tmp/$CI_COMMIT_SHA http://fake.io
    - ./build/linux-amd64-gitlab-ci-helper envs list


